# 프론트엔드 개발서버 도커 컴포즈

services:
  front: 
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
      env:        
      args:
        - DEV_SERVER_FULLCHAIN_PEM=${DEV_SERVER_FULLCHAIN_PEM}
        - DEV_SERVER_PRIVKEY_PEM=${DEV_SERVER_PRIVKEY_PEM}
        - SERVER_OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}
    image: sjhn/gongnomok-frontend:dev-1.2.1
    restart: always
    ports:
      - 80:80
      - 443:443

