# 프론트엔드 서버 도커 컴포즈

services:
  front: 
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    image: sjhn/gongnomok-frontend:prod-1.2.1
    restart: always
    ports:
      - 80:80
      - 443:443
