# 프론트엔드 개발서버 도커 컴포즈

services:
  front: 
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev        
      args:
        - SSL_FULLCHAIN=${SSL_FULLCHAIN}
        - SSL_PRIVKEY=${SSL_PRIVKEY}
        - SERVER_OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}
    image: sjhn/gongnomok-frontend:dev-latest
    restart: always
    ports:
      - 80:80
      - 443:443

