FROM node:20.11.0-bullseye as builder
WORKDIR /frontend

ENV VITE_REQUEST_API_URL=https://dev.gongnomok.com
# 자산은 같은 origin 의 frontend/public/* 에서 직접 서빙 (assets.gongnomok.com 더이상 사용 안함).
ENV VITE_ASSETS_URL=

COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.18.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/conf.d/*
COPY ./nginx/dev/default.conf /etc/nginx/conf.d/

RUN mkdir /etc/secret
RUN chmod 755 /etc/secret

ARG SSL_FULLCHAIN
ARG SSL_PRIVKEY
ARG SERVER_OPTIONS_SSL_NGINX

ENV FULLCHAIN=${SSL_FULLCHAIN}
ENV PRIVKEY=${SSL_PRIVKEY}
ENV OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}

RUN echo -n "${FULLCHAIN}" > /etc/secret/fullchain-dev.pem
RUN echo -n "${PRIVKEY}" > /etc/secret/privkey-dev.pem
RUN echo -n "${OPTIONS_SSL_NGINX}" > /etc/secret/options-ssl-nginx.conf

COPY --from=builder /frontend/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]  