# 프론트엔드 운영환경 도커 컴포즈

services:
  front: 
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
      args:
        - PROD_SERVER_FULLCHAIN_PEM=${PROD_SERVER_FULLCHAIN_PEM}
        - PROD_SERVER_PRIVKEY_PEM=${PROD_SERVER_PRIVKEY_PEM}
        - SERVER_OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}
    image: sjhn/gongnomok-frontend:prod-latest
    restart: always
    ports:
      - 80:80
      - 443:443