FROM node:20.11.0-bullseye as builder
WORKDIR /frontend
COPY ./frontend .
RUN npm install
RUN npm run build

FROM nginx:1.18.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/conf.d/*
COPY ./frontend/nginx/dev/default.conf /etc/nginx/conf.d/

RUN mkdir /etc/secret
RUN chmod 755 /etc/secret

ARG DEV_SERVER_FULLCHAIN_PEM
ARG DEV_SERVER_PRIVKEY_PEM
ARG SERVER_OPTION_SSL_NGINX

ENV FULLCHAIN_PEM=${DEV_SERVER_FULLCHAIN_PEM}
ENV PRIVKEY=${DEV_SERVER_PRIVKEY_PEM}
ENV OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}

RUN echo ${FULLCHAIN_PEM} > /etc/secret/fullchain-dev.pem
RUN echo ${PRIVKEY} > /etc/secret/privkey-dev.pem
RUN echo ${OPTIONS_SSL_NGINX} > /etc/secret/options-ssl-nginx.conf

# COPY ./secret/fullchain-dev.pem /etc/secret/
# COPY ./secret/options-ssl-nginx.conf /etc/secret/
# COPY ./secret/privkey-dev.pem /etc/secret/

COPY --from=builder ./frontend/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]  