FROM node:20.11.0-bullseye as builder
WORKDIR /frontend
COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.18.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/conf.d/*
COPY ./default-dev.conf /etc/nginx/conf.d/

RUN mkdir /etc/secret
RUN chmod 755 /etc/secret

COPY ./secret/fullchain.pem /etc/secret/
COPY ./secret/options-ssl-nginx.conf /etc/secret/
COPY ./secret/privkey.pem /etc/secret/

COPY --from=builder frontend/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]