services:
  front:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sjhn/gongnomok-frontend:prod-1.2.1
    restart: always
    ports:
      - 80:80
      - 443:443