version: "1.2.3"
services:
  back:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: sjhn/gongnomok-backend:dev-1.3.0
    restart: always
    ports:
      - 8080:8080 # tomcat
      - 80:80
      # - 8000:8000
  front:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: sjhn/gongnomok-frontend:dev-1.2.1
    restart: always
    ports:
      - 80:80 # http
      - 443:443 # https
