# CDN 서버 도커 컴포즈
services:
  cdn:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - SSL_FULLCHAIN=${SSL_FULLCHAIN}
        - SSL_PRIVKEY=${SSL_PRIVKEY}
        - SERVER_OPTIONS_SSL_NGINX=${SERVER_OPTIONS_SSL_NGINX}
    image: sjhn/gongnomok-cdn:latest
    restart: always
    ports:
      - 80:80
      - 443:443