# FROM openjdk:17-oracle as builder
# WORKDIR /backend

# COPY gradlew .
# COPY gradle gradle
# COPY build.gradle .
# COPY . .

# RUN microdnf install findutils
# RUN chmod +x ./gradlew
# RUN ./gradlew clean build

# FROM openjdk:17-oracle
# COPY /build/libs/gongnomok-app.jar ./app-dev-1.1.4.jar
# ENTRYPOINT [ "java", "-Dspring.profiles.active=dev", "-jar", "/app-dev-1.1.4.jar" ]
# VOLUME [ "/tmp" ]

FROM openjdk:17-oracle as builder
WORKDIR /backend
ADD https://github.com/pinpoint-apm/pinpoint/releases/download/v2.5.3/pinpoint-agent-2.5.3.tar.gz /usr/local
RUN tar -zxvf /usr/local/pinpoint-agent-2.5.3.tar.gz -C /usr/local

# 핀포인트 설정정보 업데이트
RUN sed -i 's/profiler.transport.grpc.collector.ip=127.0.0.1/profiler.transport.grpc.collector.ip=34.47.102.41/g' /usr/local/pinpoint-agent-2.5.3/pinpoint-root.config
RUN sed -i 's/profiler.collector.ip=127.0.0.1/profiler.collector.ip=34.47.102.41/g' /usr/local/pinpoint-agent-2.5.3/pinpoint-root.config

ARG JAR_FILE=build/lib/gongnomok-app.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8000

ENTRYPOINT [ "java", "-jar", \
"javaagent:/usr/local/pinpoint-agent-2"

" ]

# COPY /build/libs/gongnomok-app.jar ./app-dev-1.1.4.jar
# ENTRYPOINT [ "java", "-Dspring.profiles.active=dev", "-jar", "/backend/app-dev-1.1.4.jar" ]

VOLUME [ "/tmp" ]