FROM openjdk:17-oracle as builder
# WORKDIR /backend

# COPY https://github.com/pinpoint-apm/pinpoint/releases/download/v2.5.3/pinpoint-agent-2.5.3.tar.gz /usr/local
# RUN tar -zxvf /usr/local/pinpoint-agent-2.5.3.tar.gz -C /usr/local

COPY ./pinpoint-agent-2.5.3 /user/local

# 핀포인트 설정정보 업데이트
RUN sed -i 's/profiler.transport.grpc.collector.ip=127.0.0.1/profiler.transport.grpc.collector.ip=172.30.1.255/g' /usr/local/pinpoint-agent-2.5.3/pinpoint-root.config
RUN sed -i 's/profiler.collector.ip=127.0.0.1/profiler.collector.ip=172.30.1.255/g' /usr/local/pinpoint-agent-2.5.3/pinpoint-root.config

ARG JAR_FILE=build/libs/gongnomok-app.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8000

ENTRYPOINT [ "java", "-jar", \
"javaagent:/usr/local/pinpoint-agent-2.5.3/pinpoint-bootstrap-2.5.3", \
"-Dpinpoint.applicationName=gongnomok", \
"-Dpinpoint.config=/usr/local/pinpoint-agent-2.5.3/pinpoint-root.config", \
"-Dspring.profiles.active=dev", \
"/app.jar" ]