services:
  back:
    platform: linux/amd64
    build:
      # context: ./backend
      dockerfile: Dockerfile.dev
    image: sjhn/gongnomok-backend:dev-latest
    restart: always
    ports:
      - 8080:8080
      - 80:80