services:
  back:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: ./backend/docker/dev.dockerfile
      args:
        - MASTER_DB_URL=${MASTER_DB_URL}
        - SLAVE1_DB_URL=${SLAVE1_DB_URL}
        - SLAVE2_DB_URL=${SLAVE2_DB_URL}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    image: sjhn/gongnomok-backend:dev-latest
    restart: always
    ports:
      - 8080:8080